// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTl1drpCoh0gC8UpEkCo3Q4Iq5lSgKung',
    appId: '1:993951423136:web:fa9a43c0bd71a117c987c5',
    messagingSenderId: '993951423136',
    projectId: 'gyanapp-d54c8',
    authDomain: 'gyanapp-d54c8.firebaseapp.com',
    storageBucket: 'gyanapp-d54c8.firebasestorage.app',
    measurementId: 'G-YG52HZLPNL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCjaWdwcoZre_-mWVc7w58XL7KGr90b08',
    appId: '1:993951423136:android:3cb650747a3b75d3c987c5',
    messagingSenderId: '993951423136',
    projectId: 'gyanapp-d54c8',
    storageBucket: 'gyanapp-d54c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhul0T5JKVtkax84w0X0lTdTCmtGZwKS0',
    appId: '1:993951423136:ios:1c883eb0de898ac6c987c5',
    messagingSenderId: '993951423136',
    projectId: 'gyanapp-d54c8',
    storageBucket: 'gyanapp-d54c8.firebasestorage.app',
    iosBundleId: 'com.example.gyanApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhul0T5JKVtkax84w0X0lTdTCmtGZwKS0',
    appId: '1:993951423136:ios:1c883eb0de898ac6c987c5',
    messagingSenderId: '993951423136',
    projectId: 'gyanapp-d54c8',
    storageBucket: 'gyanapp-d54c8.firebasestorage.app',
    iosBundleId: 'com.example.gyanApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTl1drpCoh0gC8UpEkCo3Q4Iq5lSgKung',
    appId: '1:993951423136:web:92279dbdb9919ce3c987c5',
    messagingSenderId: '993951423136',
    projectId: 'gyanapp-d54c8',
    authDomain: 'gyanapp-d54c8.firebaseapp.com',
    storageBucket: 'gyanapp-d54c8.firebasestorage.app',
    measurementId: 'G-XHR4XLQ1MQ',
  );
}
